name-template: 'Shadowgram v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: 'v'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
no-changes-template: '- No pull-request changes detected.'
template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Fixes'
    labels:
      - 'bug'
      - 'bugfix'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'ci'
      - 'dependencies'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'Other Changes'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'feat'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'bugfix'
      - 'fix'
      - 'chore'
      - 'ci'
      - 'dependencies'
      - 'maintenance'
      - 'documentation'
      - 'docs'
  default: patch

exclude-labels:
  - 'skip-changelog'
